<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <UserSecretsId>Template.Service.Api-CrmClient</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="8.2.0" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.23.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.ApplicationInsights" Version="5.0.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Framework.Logger\Framework.Logger.csproj" />
    <ProjectReference Include="..\Template.Service.DependencyInjection\Template.Service.DependencyInjection.csproj" />
    <ProjectReference Include="..\Template.Service.BusinessModel\Template.Service.BusinessModel.csproj" />
    <ProjectReference Include="..\Template.Service.BusinessLogic.Interfaces\Template.Service.BusinessLogic.Interfaces.csproj" />
    <ProjectReference Include="..\Template.Service.Services.Interfaces\Template.Service.Services.Interfaces.csproj" />
    <ProjectReference Include="..\Template.Service.Mapper\Template.Service.Mapper.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Logger\" />
  </ItemGroup>

</Project>

